monitor/account/urls.py
from django.urls import path
from . import views


app_name = 'account'
urlpatterns = [
    path('', views.login_view, name='login'),
    path('logout/', views.logout_view, name='logout'),
]

monitor/deployer/urls.py
from django.urls import path

from . import views

app_name = 'deploy'
urlpatterns = [
    path('react/', views.ReactDeployedApps.as_view(), name='react'),
    path('react/new/', views.ReactDeployNewapp.as_view(), name='react-new'),
    path(
        'react/app/<str:slug>/',
        views.DeployDetail.as_view(), name='react-app'),
    path(
        'react/deploy/app/<str:slug>/',
        views.deploy_app, name='deploy-react-app'),
    path(
        'react/pull/app/<str:slug>/',
        views.pull_app_repository, name='pull-app'),
    path(
        'react/deploy/log/<str:slug>/',
        views.FetchDeployLog.as_view(), name='deploy-app-logs'),
    path(
        'react/deploy/app/setup/auto-redeploy/<str:slug>/',
        views.setup_auto_redeploy_app, name='setup-redeploy'),
]

monitor/panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'
urlpatterns = [
    # Github webhook
    path(
        'github/payload/',
        views.github_receive_webhook, name='github-webhook'),

    # Logged in views
    path(
        '', views.Dashboard.as_view(), name='dashboard'),

    path(
        'server/<str:slug_name>/',
        views.ServerPage.as_view(), name='server_page'),
    path(
        'server/websites/refresh/<str:slug_name>/',
        views.update_server_websites, name='websites_refresh'),
    path(
        'server/websites/recheck/<str:slug_name>/',
        views.recheck_server_websites, name='websites_recheck'),

    path(
        'services/<str:service_name>/',
        views.ServiceLog.as_view(), name='service'),
    path(
        'service/stat/<str:service_name>/',
        views.recheck_service_status, name='recheck_service'),
    path('service/logs/', views.get_logs_view, name='get_logs'),

    path(
        'server/<str:server_name>/websites/<str:conf_filename>/',
        views.WebsiteLog.as_view(), name='website'),
    path(
        'websites/recheck/<str:conf_filename>/',
        views.recheck_website_status, name='recheck_website'),
    path(
        'website/logs/<str:conf_filename>/',
        views.get_websites_logs_view, name='get_log_website'),

    path('domain/', views.DomainList.as_view(), name='domain-list'),
    path(
        'domain/update/',
        views.update_domain_list, name='domain-list-update'),
    path(
        'domain/<int:domain_id>/subdomains/',
        views.DomainDetail.as_view(), name='domain-detail'),
    path(
        'domain/<int:domain_id>/subdomains/update/',
        views.update_subdomain_list, name='subdomain-list-update'),

    path(
        'file-manager/',
        views.FileManagerView.as_view(), name='file-manager'),


    # Github
    path(
        'github/accounts/',
        views.GithubAccountList.as_view(), name='github_list'),
    path(
        'github/accounts/create/',
        views.GithubAccountCreate.as_view(), name='github_account_create'),
    path(
        'github/accounts/<str:username>/',
        views.GithubAccountDetail.as_view(), name='github_detail'),
    path(
        'github/accounts/update-accounts/<str:username>/',
        views.update_github_accounts, name='update_github_accounts'),
    path(
        'github/accounts/update/<str:username>/',
        views.GithubAccountUpdate.as_view(), name='github_update'),
    path(
        'github/accounts/delete/<str:username>/',
        views.delete_github_account, name='github_delete'),

    path(
        'github/accounts/update/<str:username>/user/<str:account_name>/',
        views.GithubAccountUserUpdate.as_view(), name='github_update_user'),
    path(
        'github/accounts/update/<str:username>/user/repository/<str:account_name>/',  # noqa
        views.update_repos, name='update_repos'),
]

monitor/panel/models.py
from typing import Dict, List, Type

from django.conf import settings
from django.db import models
from django.db.models import QuerySet
from django.utils.text import slugify
from utils.general import merge_querysets
from utils.general import printt as print  # noqa
from utils.github import GithubClient
from utils.linode import linodeClient
from utils.logger import err_logger, logger  # noqa
from utils.model_mixins import ModelChangeFunc
from utils.process import ServerProcess
from utils.typing import DnsType

# NOTE: Create custom model field for comma separated fields


class Server(ModelChangeFunc):
    """
    Will require Server IP address for connecting to server,
    Required to select a default server implementation (nginx or apache ...)
    """
    WEB_SERVER = (
        ('apache', 'Apache'),
        ('nginx', 'Nginx'),
    )

    ip_address = models.GenericIPAddressField(unique=True)
    web_server = models.CharField(choices=WEB_SERVER, max_length=30)
    server_os_name = models.CharField(max_length=100, blank=True)
    server_os_version = models.CharField(max_length=100, blank=True)
    server_os_url = models.URLField(blank=True)

    name = models.CharField(
        help_text='Unique name for identifying server',
        max_length=45, unique=True)
    slug_name = models.SlugField(unique=True, blank=True)

    # Login credentials
    username = models.CharField(max_length=255)
    password = models.CharField(max_length=1024)

    __process: Type[ServerProcess] = None

    def create_process(self) -> Type[ServerProcess]:
        """
        Create a server process
        """

        return ServerProcess(
            host=self.ip_address,
            username=self.username,
            password=self.password,
            web_server=self.web_server
        )

    def get_process(self) -> Type[ServerProcess]:
        """
        Get a server process
        """

        if self.__process is None:
            self.__process = self.create_process()
        return self.__process

    def get_connected_process(self) -> Type[ServerProcess]:
        """
        Get a connected server process
        """

        client = self.get_process()
        client.create_client()
        return client

    def update_slug(obj):
        obj.slug_name = slugify(obj.name)

    def update_server_details(self):
        self.server_os_name = self.get_connected_process().get_server_name()
        self.server_os_version = self.get_connected_process()\
            .get_server_version()
        self.server_os_url = self.get_connected_process()\
            .get_server_os_home_url()

    monitor_change = {
        'name': update_slug,
        'ip_address': update_slug,
    }

    def __str__(self) -> str:
        return self.name

    def recheck(self):
        """
        Recheck the status of the websites
        under this server
        """

        websites = self.website_set.all()
        for website in websites:
            website.recheck()

    def get_home_directory(self):
        """
        Get server home directory
        """
        return self.get_process().get_home_directory()

    def get_enabled_sites(self) -> list:
        """
        Get enabled websites for default web server

        :return: Return enabled websites for default web server
        :rtype: _type_
        """

        client = self.get_connected_process()
        return client.fetch_enabled_sites()

    def parse_website_data(self, data: Dict[str, str]) -> dict:
        """
        Parse out the data from dictionary for website
        instance update

        :param data: Data gotten from get_enabled_sites
        :type data: Dict[str, str]
        :return: Cleaned and parsed data
        :rtype: dict
        """

        client = self.get_connected_process()
        return client.parse_website_data(data)

    def save(self, *args, **kwargs):
        if not self.server_os_name:
            self.update_server_details()
        super().save(*args, **kwargs)


class Domain(models.Model):
    """
    Domain model for top level domains
    """

    DOMAIN_PROVIDER = (
        ('1', 'Linode',),
        ('2', 'GoDaddy',),
        ('3', 'Namecheap',),
    )

    __DOMAIN_PROVIDER_DNS = {
        '1': linodeClient
    }

    domain = models.URLField()
    domain_id = models.IntegerField(unique=True)
    status = models.CharField(max_length=50)
    status_tag = models.CharField(max_length=50)
    soa_email = models.EmailField()
    domain_provider = models.CharField(choices=DOMAIN_PROVIDER, max_length=1)

    def __str__(self):
        return self.domain

    @classmethod
    def get_dns_clients(cls) -> Dict[str, Type[DnsType]]:
        """
        Get Domain name clients and id available

        :return: Domain name clients api instances with id
        :rtype: Dict[str, Type[DnsType]]
        """
        return cls.__DOMAIN_PROVIDER_DNS

    def get_subdomain_js_string(self) -> str:
        """
        Return domain subdomains and record id
        Created for deploy page js code to get domain
        names with their record id
        """

        # Get the subdomains
        subdomains = Subdomain.objects.filter(domain_id=self.domain_id)

        # Result list
        result = []

        for subdomain in subdomains:
            # Clean subdomain name
            sub_name = subdomain.name
            if sub_name:
                name = f"{sub_name}.{self.domain}"
            else:
                name = self.domain

            record_id = subdomain.record_id

            result.append(f"{name}*{record_id}")

        return '?'.join(result)

    def get_dns_client(self) -> Type[DnsType]:
        return self.__DOMAIN_PROVIDER_DNS.get(self.domain_provider)


class Subdomain(models.Model):
    """
    Subdomain model for domain A record
    """
    record_id = models.IntegerField(unique=True)
    domain_id = models.IntegerField()
    # TODO: Use foriegn key here
    name = models.CharField(max_length=255)
    target = models.GenericIPAddressField()

    def get_name(self):
        """
        Get the subdomain name
        """

        if self.name == '.':
            return ''
        return self.name

    def __str__(self):
        return self.name


class GithubAccount(ModelChangeFunc):
    """
    Github account for users model

    :param username: Username of the github account
    :type username: str
    :param password: Personal Access Token of github account
    :type password: str
    :param white_list_organizations: Comma separated list of organization
    names that should be listed with their repositories
    (Names of organizations are case sensitive as required by Github)
    :type white_list_organizations: str
    :param black_list_organizations: Comma separated list of organization
    names that should not be listed with their repositories
    (Names of organizations are case sensitive as required by Github)
    :type black_list_organizations: str
    :param active: Active github accounts
    :type active: bool
    :param created: When github account was connected on the system
    :type created: datetime
    :param updated: Last time github account was updated
    :type updated: datetime
    """

    username = models.CharField(max_length=255, unique=True)
    password = models.CharField(
        max_length=255,
        help_text='''Github account personal access token,
        it will be helpful if this access token will live for a long time''')

    # if any organizations are listed here they will be
    # the only oranizations that their repositories
    # can be gotten from github
    white_list_organizations = models.TextField(
        blank=True,
        help_text="""Organization names should be valid names
         and comma separated""")

    # if any organizations are listed here they will be
    # the only oranizations that their repositories
    # will not be gotten from github
    black_list_organizations = models.TextField(
        blank=True,
        help_text="""Organization names should be
        valid names and comma separated""")

    # NOTE: if white list and black list have organizations
    # listed in them, White list takes precedence over black list

    active = models.BooleanField(default=True)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    # Monitor change implementations
    def update_github_accounts_white(obj):
        obj.update_account_users_whitelist()

    def update_github_accounts_black(obj):
        obj.update_account_users_blacklist()

    monitor_change = {
        'white_list_organizations': update_github_accounts_white,
        'black_list_organizations': update_github_accounts_black,
    }

    @property
    def github_client(self) -> GithubClient:
        """
        Create github client for this account
        """

        return GithubClient(self.password)

    def get_github_link(self) -> str:
        """
        Return github username link

        :return: github username link
        :rtype: str
        """
        return f"https://github.com/{self.username}"

    def list_comma_field(self, field_name: str) -> list:
        """
        Get the comma separated field in the database
        as a list of items
        """

        lists = []

        field_value: str = getattr(self, field_name)
        if field_value:
            lists: List[str] = field_value.split(',')
            lists = [item.strip() for item in lists]

        return lists

    def get_white_list(self):
        """
        Get the list for whitelist
        """
        return self.list_comma_field('white_list_organizations')

    def get_black_list(self):
        """
        Get the list for blacklist
        """
        return self.list_comma_field('black_list_organizations')

    def update_account_users_blacklist(self):
        """
        Updates accounts by blacklist added
        """
        black_list = self.get_black_list()

monitor/panel/templates/panel/domains.html
{% extends 'panel/base.html' %}


{% block content %}
    <div class="card mb-0">
        <div class="card-header py-3 d-flex align-items-center justify-content-between">
            <h5 class="mini_tabs_head">Domains List</h5>
            <a href="{% url 'panel:domain-list-update' %}" class='btn btn-sm btn-secondary reload-btn'> <span class='fa fa-refresh'></span> Reload</a>
        </div>
    </div>

    <div class="card-body domain-name-card-body manage-link-a">
        <table class="table table-hover">
            <thead class="">
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">DNS Provider</th>
                    <th scope="col">Domain name</th>
                    <th scope="col">SOA Email</th>
                    <th scope="col">Status</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>

                
                {% if list_domains_processed %}

                    {% for domain in list_domains_processed %}
                        <tr>
                            <th scope="row">{{ forloop.counter }}</th>
                            <th>{{ domain.get_domain_provider_display }}</th>
                            <td><a href="{% url 'panel:domain-detail' domain.domain_id %}" class="text-decoration-none">{{ domain.domain }}</a></td>
                            <td>{{ domain.soa_email }}</td>
                            <td><span class="badge bg-{{ domain.status_tag }}">{{ domain.status }}</span></td>
                            <td><a href="{% url 'panel:domain-detail' domain.domain_id %}" class="btn btn-sm btn-primary">Manage</a></td>
                        </tr>
                    {% endfor %}
                    
                {% else %}

                    <h2>No domains available</h2>
                    
                {% endif %}
                    
                
            </tbody>
        </table>
    </div>
{% endblock content %}

monitor/panel/templates/panel/github_account.html
{% extends 'panel/base.html' %}


{% block content %}

<div class="my-4 d-flex">
    <div>
        <h4 class="mb-3">{{ github_account.username }}</h4>

        <p class="fw-light mb-2">Created: {{ github_account.created }}</p>
        <p class="fw-light mb-2">Last Updated: {{ github_account.updated }}</p>
    </div>

    <div class="buttons side-bar-btns ms-auto">
        <a href="{% url 'panel:github_update' github_account.username %}" class="btn btn-primary btn-sm">Edit</a>
        <a href="{% url 'panel:github_delete' github_account.username %}" class="btn btn-danger btn-sm are-you-sure-delete">Delete</a>
        <a href="{% url 'panel:update_github_accounts' github_account.username %}" class="btn btn-primary btn-sm">Update Accounts</a>
    </div>
</div>


{% for user_account in repository_users %}


    {% with user_account.repository_set.all as repository %}

        <div class="card mb-3">
            <div class="card-header py-3 d-flex">
                <h6 class="mini_tabs_head">{{ user_account.user }} - Repository ({{ repository.count }})</h6>

                <div class="ms-auto d-flex align-items-center">
                    <a href="{% url 'panel:github_update_user' github_account.username user_account.user %}" class="btn btn-sm btn-primary">Edit</a>
                    <a href="{% url 'panel:update_repos' github_account.username user_account.user %}" class="btn btn-sm btn-secondary ms-2">Update Repository</a>
                </div>
            </div>

            <div class="card-body">
                <div class="mini_tabs">

                    {% for repo in repository %}
                    
                        <a href="{{ repo.clone_url }}" target="_blank" class="mini_tab">
                            <h6>{{ repo.name }}</h6>
                            <p>Master Branch: {{ repo.default_branch }}</p>
                            <p>Branches: {{ repo.branch_count }}</p>
                        </a>

                    {% endfor %}

                    {% if repository.count == 0 %}
                        <h5 class='py-4'>No Repository added yet</h5>
                    {% endif %}

                </div>
            </div>
        </div>
        
    {% endwith %}
    
    
{% endfor %}



{% if repository_users.count == 0 %}
    <div class="bg-secondary text-light rounded p-4 my-5">
        <h5>No Github Account Users added yet</h5>
    </div>
{% endif %}
    

{% endblock content %}

monitor/panel/templates/panel/index.html
{% extends 'panel/base.html' %}
{% load static %}

{% block content %}



{% if perms.panel.view_server %}
    <div class="card">
        <div class="card-header b-l-primary border-3 d-flex">
            <h5 class="mini_tabs_head">Servers</h5>
        </div>

        <div class="card-body">
            <div class="mini_tabs">

                {% for server in servers %}
                
                <a href="{% url 'panel:server_page' server.slug_name %}" class="mini_tab">
                    <h6>{{ server.name }}</h6>
                    <p>{{ server.ip_address }}</p>
                </a>

                {% endfor %}

                {% if servers.count == 0 %}
                <h5 class='py-4'>No Servers added yet</h5>
                {% endif %}

            </div>
        </div>
    </div>
{% endif %}
    


<div class="card mt-4">
    <div class="card-header b-l-primary border-3 d-flex">
        <h5 class="mini_tabs_head">All Websites</h5>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for website in websites %}
            
            <a href="{% url 'panel:website' website.server.slug_name website.conf_filename %}" class="mini_tab 
            {% if not website.active %}
                not_active
            {% endif %}
                ">
                <h6>{{ website.name }}</h6>
                <p>{{ website.last_checked }}</p>
            </a>

            {% endfor %}

            {% if websites.count == 0 %}
            <h5 class='py-4'>No websites added yet</h5>
            {% endif %}

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header b-l-primary border-3 d-flex">
        <h5 class="mini_tabs_head">General</h5>
    </div>

    <div class="card-body">
        <div class="mini_tabs">
            
            <a href="{% url 'panel:domain-list' %}" class="mini_tab">
                <h6>Domain Lists</h6>
            </a>

            <a href="#" class="mini_tab">
                <h6>File Manager</h6>
                <p class='fw-bold text-muted'>Coming soon!</p>
            </a>

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header b-l-primary border-3 d-flex">
        <h5>Github Accounts</h5>

        <div class="ms-auto d-flex align-items-center">
            <a href="{% url 'panel:github_account_create' %}" class="btn btn-gradient">Add Github Account</a>
        </div>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for github_account in github_accounts %}
            
                <a href="{% url 'panel:github_detail' github_account.username %}" class="mini_tab">
                    <h6>{{ github_account.username }}</h6>
                    <p>Created: <br> {{ github_account.created }}</p>
                </a>

            {% endfor %}

            {% if github_accounts.count == 0 %}
                <h5 class='py-4'>No Github accounts added yet</h5>
            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}

monitor/panel/templates/panel/old_base.html
{% load static %}

<!doctype html>
<html lang="en">
    <head>
        <!-- Required meta tags -->
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">

        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
        <link rel="stylesheet" href="{% static 'css/main.css' %}">


        <!-- Icons -->
        <link rel="stylesheet" href="{% static 'fonts/themify-icons/themify-icons.css' %}">
        <link rel="stylesheet" href="{% static 'css/font-awesome.min.css' %}" />
        
        {% if title %}
        <title>Server Monitor - {{ title }}</title>
        {% else %}
        <title>Server Monitor</title>
        {% endif %}

    </head>
    <body>

        <div id='loader_container'>

			<div id='loader_span'></div>

		</div>


        <nav class="navbar navbar-dark bg-dark py-3">
            <div class="container-fluid d-flex align-items-center justify-content-between">
                
                
                {% if server %}
                    <a href="{% url 'panel:dashboard' %}" class="navbar-brand mb-0 h2">{{ server.name.capitalize }} Dashboard</a>
                {% else %}
                    <a href="{% url 'panel:dashboard' %}" class="navbar-brand mb-0 h2">Monitor Panel</a>
                {% endif %}

                <div class="d-flex">
                    {% if server %}
                        <a href="{% url 'panel:server_page' server.slug_name %}" class="btn btn-md btn-primary">Server Dashboard</a>
                    {% endif %}

                    <a href="{% url 'account:logout' %}" class="btn btn-md btn-danger ms-2">Logout</a>
                </div>
            </div>
        </nav>

        {% if messages %}
            {% for message in messages %}
            <div class="alert alert-{{ message.tags }}">
                {{message}}
            </div>
            {% endfor %}
        {% endif %}

        <div class="alerts-container">
        
        </div>


        <section id="tabs">
            <div class="container-fluid">
                <div class="row">

                    <div class="col-lg-8 col-md-8 col-sm-12 my-1">

                        {% block content %}{% endblock content %}

                    </div>

                    {% include 'panel/sidebar.html' %}

                </div>
            </div>
        </section>

        <script src="https://code.jquery.com/jquery-3.6.0.js" integrity="sha256-H+K7U5CnXl1h5ywQfKtSj8PCmoN9aaq30gDh27Xc0jk=" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>

        <script src="{% static 'js/main.js' %}"></script>

    </body>
</html>

monitor/panel/templates/panel/old_index.html
{% extends 'panel/base.html' %}


{% block content %}



{% if perms.panel.view_server %}
<div class="card mt-4">
    <div class="card-header py-3">
        <h6 class="mini_tabs_head">Servers</h6>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for server in servers %}
            
            <a href="{% url 'panel:server_page' server.slug_name %}" class="mini_tab">
                <h6>{{ server.name }}</h6>
                <p>{{ server.ip_address }}</p>
            </a>

            {% endfor %}

            {% if servers.count == 0 %}
            <h5 class='py-4'>No Servers added yet</h5>
            {% endif %}

        </div>
    </div>
</div>
{% endif %}
    


<div class="card mt-4">
    <div class="card-header py-3">
        <h6 class="mini_tabs_head">All Websites</h6>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for website in websites %}
            
            <a href="{% url 'panel:website' website.server.slug_name website.conf_filename %}" class="mini_tab 
            {% if not website.active %}
                not_active
            {% endif %}
                ">
                <h6>{{ website.name }}</h6>
                <p>{{ website.last_checked }}</p>
            </a>

            {% endfor %}

            {% if websites.count == 0 %}
            <h5 class='py-4'>No websites added yet</h5>
            {% endif %}

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header py-3">
        <h6 class="mini_tabs_head">General</h6>
    </div>

    <div class="card-body">
        <div class="mini_tabs">
            
            <a href="{% url 'panel:domain-list' %}" class="mini_tab">
                <h6>Domain Lists</h6>
            </a>

            <a href="#" class="mini_tab">
                <h6>File Manager</h6>
                <p class='fw-bold text-muted'>Coming soon!</p>
            </a>

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header py-3 d-flex">
        <h6 class="mini_tabs_head">Github Accounts</h6>

        <div class="ms-auto d-flex align-items-center">
            <a href="{% url 'panel:github_account_create' %}" class="btn btn-sm btn-primary">Add Github Account</a>
        </div>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for github_account in github_accounts %}
            
                <a href="{% url 'panel:github_detail' github_account.username %}" class="mini_tab">
                    <h6>{{ github_account.username }}</h6>
                    <p>Created: <br> {{ github_account.created }}</p>
                </a>

            {% endfor %}

            {% if github_accounts.count == 0 %}
                <h5 class='py-4'>No Github accounts added yet</h5>
            {% endif %}

        </div>
    </div>
</div>

{% endblock content %}

monitor/panel/templates/panel/server_page.html
{% extends 'panel/base.html' %}


{% block content %}

<div class="card">
    <div class="card-header b-l-primary border-3">
        <h5 class="mini_tabs_head">Services</h5>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for service in services %}
            
            <a href="{% url 'panel:service' service.service_name %}" class="mini_tab">
                <h6>{{ service.name }}</h6>
            </a>

            {% endfor %}

            {% if services.count == 0 %}
            <h5 class='py-4'>No services added yet</h5>
            {% endif %}

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header b-l-primary border-3 d-flex align-items-center">
        <h5 class="mini_tabs_head">Websites</h5>
        <div class="ms-auto d-flex align-items-center">
            <a href="{% url 'panel:websites_recheck' server.slug_name %}" class="btn btn-sm btn-primary">Recheck</a>
            <a href="{% url 'panel:websites_refresh' server.slug_name %}" class="btn btn-sm btn-primary ms-2">Refresh</a>
        </div>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            {% for website in websites %}
            
            <a href="{% url 'panel:website' server.slug_name website.conf_filename %}" class="mini_tab
            {% if not website.active %}
                not_active
            {% endif %}
            ">
                <h6>{{ website.name }}</h6>
                
                {% if website.last_checked is None %}
                    <p>Not Checked Yet</p>
                {% else %}
                    <p>{{ website.last_checked }}</p>
                {% endif %}
                
            </a>

            {% endfor %}

            {% if websites.count == 0 %}
            <h5 class='py-4'>No websites added yet</h5>
            {% endif %}

        </div>
    </div>
</div>

<div class="card mt-4">
    <div class="card-header b-l-primary border-3">
        <h5 class="mini_tabs_head">General</h5>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            
            <a href="{% url 'panel:domain-list' %}" class="mini_tab">
                <h6>Domain Lists</h6>
            </a>

            <a href="#" class="mini_tab">
                <h6>File Manager</h6>
                <p class='fw-bold text-muted'>Coming soon!</p>
            </a>

        </div>
    </div>
</div>


<div class="card mt-4">
    <div class="card-header b-l-primary border-3">
        <h5 class="mini_tabs_head">Deploy Apps</h5>
    </div>

    <div class="card-body">
        <div class="mini_tabs">

            
            <a href="#" class="mini_tab">
                <h6>Python</h6>
                <p class='fw-bold text-muted'>Coming soon!</p>
            </a>

            <a href="#" class="mini_tab">
                <h6>PHP</h6>
                <p class='fw-bold text-muted'>Coming soon!</p>
            </a>

            <a href="{% url 'deploy:react' %}" class="mini_tab">
                <h6>React</h6>
            </a>

        </div>
    </div>
</div>

{% endblock content %}