monitor/deployer/urls.py
from django.urls import path

from . import views

app_name = 'deploy'
urlpatterns = [
    path('react/', views.ReactDeployedApps.as_view(), name='react'),
    path('react/new/', views.ReactDeployNewapp.as_view(), name='react-new'),
    path(
        'react/app/<str:slug>/',
        views.DeployDetail.as_view(), name='react-app'),
    path(
        'react/deploy/app/<str:slug>/',
        views.deploy_app, name='deploy-react-app'),
    path(
        'react/pull/app/<str:slug>/',
        views.pull_app_repository, name='pull-app'),
    path(
        'react/deploy/log/<str:slug>/',
        views.FetchDeployLog.as_view(), name='deploy-app-logs'),
    path(
        'react/deploy/app/setup/auto-redeploy/<str:slug>/',
        views.setup_auto_redeploy_app, name='setup-redeploy'),
]

monitor/panel/urls.py
from django.urls import path
from . import views


app_name = 'panel'
urlpatterns = [
    # Github webhook
    path(
        'github/payload/',
        views.github_receive_webhook, name='github-webhook'),

    # Logged in views
    path(
        '', views.Dashboard.as_view(), name='dashboard'),

    path(
        'server/<str:slug_name>/',
        views.ServerPage.as_view(), name='server_page'),
    path(
        'server/websites/refresh/<str:slug_name>/',
        views.update_server_websites, name='websites_refresh'),
    path(
        'server/websites/recheck/<str:slug_name>/',
        views.recheck_server_websites, name='websites_recheck'),

    path(
        'services/<str:service_name>/',
        views.ServiceLog.as_view(), name='service'),
    path(
        'service/stat/<str:service_name>/',
        views.recheck_service_status, name='recheck_service'),
    path('service/logs/', views.get_logs_view, name='get_logs'),

    path(
        'server/<str:server_name>/websites/<str:conf_filename>/',
        views.WebsiteLog.as_view(), name='website'),
    path(
        'websites/recheck/<str:conf_filename>/',
        views.recheck_website_status, name='recheck_website'),
    path(
        'website/logs/<str:conf_filename>/',
        views.get_websites_logs_view, name='get_log_website'),

    path('domain/', views.DomainList.as_view(), name='domain-list'),
    path(
        'domain/update/',
        views.update_domain_list, name='domain-list-update'),
    path(
        'domain/<int:domain_id>/subdomains/',
        views.DomainDetail.as_view(), name='domain-detail'),
    path(
        'domain/<int:domain_id>/subdomains/update/',
        views.update_subdomain_list, name='subdomain-list-update'),

    path(
        'file-manager/',
        views.FileManagerView.as_view(), name='file-manager'),


    # Github
    path(
        'github/accounts/',
        views.GithubAccountList.as_view(), name='github_list'),
    path(
        'github/accounts/create/',
        views.GithubAccountCreate.as_view(), name='github_account_create'),
    path(
        'github/accounts/<str:username>/',
        views.GithubAccountDetail.as_view(), name='github_detail'),
    path(
        'github/accounts/update-accounts/<str:username>/',
        views.update_github_accounts, name='update_github_accounts'),
    path(
        'github/accounts/update/<str:username>/',
        views.GithubAccountUpdate.as_view(), name='github_update'),
    path(
        'github/accounts/delete/<str:username>/',
        views.delete_github_account, name='github_delete'),

    path(
        'github/accounts/update/<str:username>/user/<str:account_name>/',
        views.GithubAccountUserUpdate.as_view(), name='github_update_user'),
    path(
        'github/accounts/update/<str:username>/user/repository/<str:account_name>/',  # noqa
        views.update_repos, name='update_repos'),
]

monitor/deployer/models.py
from typing import Type

from django.db import models
from django.utils.text import slugify
from utils.general import cryptor
from utils.model_mixins import ModelChangeFunc
from utils.process import AppProcess, ReactProcess, ServerProcess
from utils.validators import validate_special_char


class BaseApp(ModelChangeFunc):
    STATUS = (
        ('inactive', 'Inactive',),
        ('pending', 'Pending',),
        ('deployed', 'Deployed',),
        ('failed', 'Failed',),
        ('disabled', 'Disabled',),
        # ('maintenance', 'Maintenance',),
    )

    # App type
    app_type = None

    # Server (apps can only be deployed on a server)
    server = models.ForeignKey('panel.Server', on_delete=models.CASCADE)

    # Project fields
    project_name = models.CharField(
        max_length=255, validators=[validate_special_char], unique=True)
    slug = models.SlugField(max_length=512, unique=True, blank=True)
    project_dir = models.CharField(max_length=255)
    conf_dir = models.CharField(max_length=255)
    access_log = models.CharField(max_length=255)
    error_log = models.CharField(max_length=255)

    # Repository
    repository = models.ForeignKey(
        'panel.Repository', on_delete=models.CASCADE)
    branch = models.CharField(
        max_length=50, help_text='Branch on repository to deploy,\
 this checkouts to default master branch if not specified')

    # Domain
    domain = models.ForeignKey(
        'panel.Domain', on_delete=models.SET_NULL, null=True)
    subdomain = models.ForeignKey(
        'panel.Subdomain', on_delete=models.SET_NULL, null=True)

    # Status
    status = models.CharField(
        choices=STATUS, default='inactive', max_length=255)

    # Tracking Deployment
    app_in_process = models.BooleanField(default=False)
    auto_redeploy = models.BooleanField(default=False)

    def save(self, force_insert=False, force_update=False, *args, **kwargs):
        if not self.id:
            self.slug = slugify(self.project_name)
        super().save(force_insert, force_update, *args, **kwargs)

    class Meta:
        abstract = True

    def get_app_type(self):
        return self.app_type

    def get_app_dir(self) -> str:
        return self.get_app_process().get_project_directory()

    def get_log_file(self) -> str:
        """
        Get deploy log path for current project

        :return: path
        :rtype: str
        """

        return self.get_app_process().get_log_file()

    # For status icon html classes
    def get_status_icon(self) -> Type[str | None]:
        """
        Get icon value for status

        :return: icon name
        :rtype: Type[str | None]
        """

        status_icon = {
            'inactive': 'grav',
            'pending': 'spinner',
            'deployed': 'check',
            'failed': 'bug',
            'disabled': 'times'
        }
        return status_icon.get(self.status)

    def raw_link(self) -> str:
        """
        Get the app full link

        :return: link
        :rtype: str
        """
        if self.subdomain is not None and self.domain is not None:
            return f"{self.subdomain.get_name()}.{self.domain.domain}"
        return ''

    def get_link(self) -> str:
        """
        Append http to app raw link

        :return: link
        :rtype: str
        """
        raw_link = self.raw_link()
        if raw_link:
            return f"http://{raw_link}"
        return raw_link

    @property
    def process(self) -> ServerProcess:
        return self.server.get_process()

    __app_process: AppProcess = None

    def create_app_process(self) -> AppProcess:
        return AppProcess(
            name=self.slug,
            branch=self.branch,
            clone_url=self.get_process_clone_url(),
            url=self.get_link(),
            host=self.server.ip_address,
            username=self.server.username,
            password=self.server.password,
            web_server=self.server.web_server
        )

    def get_app_process(self) -> AppProcess:
        if self.__app_process is None:
            self.__app_process = self.create_app_process()
        return self.__app_process

    def get_web_server_conf(self) -> str:
        """
        Get web server configuration for project

        :return: web server configuration path
        :rtype: str
        """
        return self.process.web_server.get_file_available_path(self.slug)

    def update_app_status(self, status: str):
        self.status = status

    def failed_deploy(self):
        self.update_app_status('failed')

    def success_deploy(self):
        self.update_app_status('deployed')

    def pending_deploy(self):
        self.update_app_status('pending')

    def get_process_clone_url(self) -> str:
        clone_url: str = self.repository.clone_url
        github_username = self.repository.github_user.get_account_name()
        github_password = cryptor.decrypt(
            self.repository.github_user.account.password)

        clone_url = clone_url.replace(
            'https://', f"https://{github_username}:{github_password}@")
        return clone_url

    def __str__(self) -> str:
        return self.project_name


class ReactApp(BaseApp):
    app_type = 'react'

    def create_app_process(self) -> ReactProcess:
        return ReactProcess(
            name=self.slug,
            branch=self.branch,
            clone_url=self.get_process_clone_url(),
            url=self.get_link(),
            host=self.server.ip_address,
            username=self.server.username,
            password=self.server.password,
            web_server=self.server.web_server
        )

    def run_pull(self):
        """
        Start git pull process for app
        """

        process: ReactProcess = self.get_app_process()
        app_logger = process.get_logger()
        app_logger.info('Started pull process')
        self.app_in_process = True
        self.pending_deploy()
        self.save()

        try:
            process.create_client()
            process.git_checkout()
            process.git_pull()
            self.success_deploy()
            app_logger.info('Respository updated.')

        except Exception as e:
            app_logger.info('Error pulling repository')
            app_logger.exception(e)
            self.failed_deploy()

        process.destroy()
        app_logger.info('Finished Pull process\n\n')
        self.app_in_process = False
        self.save()

    def deploy_process(self):
        """
        Start deploy process for app
        """

        process: ReactProcess = self.get_app_process()
        app_logger = process.get_logger()
        app_logger.info('Started deploying process')
        self.app_in_process = True
        self.pending_deploy()
        self.save()

        try:
            process.create_client()
            process.create_project_directory()
            process.git_clone()
            process.git_checkout()
            process.git_pull()
            process.npm_install()
            process.add_homepage()
            process.npm_build()
            access_log, error_log = process.configure_server()
            self.access_log = access_log
            self.error_log = error_log
            process.enable_web_server()
            process.restart_web_server()
            self.success_deploy()
            app_logger.info('Project is successfully deployed.')

        except Exception as e:
            app_logger.info(
                'Error while trying to deploy app directory on server')
            app_logger.exception(e)
            self.failed_deploy()

        process.destroy()
        app_logger.info('Finished Deploying\n\n')
        self.app_in_process = False
        self.save()

monitor/deployer/forms.py
from typing import Dict, Type, Union

from django import forms
from panel.models import Domain, Subdomain
from utils.validators import validate_special_char

from .models import ReactApp


#: Type for cleaned data returned in ReactDeployForm
CleanDataType = Dict[str, Union[str, Type[Domain], Type[Subdomain]]]


class ReactDeployForm(forms.ModelForm):
    cleaned_data: CleanDataType = {}
    domain = forms.IntegerField(required=True)
    subdomain = forms.IntegerField(required=False)
    link = forms.CharField(
        required=False,
        max_length=255, validators=[validate_special_char])

    class Meta:
        model = ReactApp
        fields = ('project_name', 'repository', 'branch',)

    def validate_git(self, data: dict):
        """
        Verify the github branch and repository

        :param data: Data from form fields
        :type data: dict
        :raises forms.ValidationError: Valid repository
        :raises forms.ValidationError: Valid branch
        """
        repository = data.get('repository')
        branch = data.get('branch')

        if not repository:
            raise forms.ValidationError(
                {'repository': 'You must select a repository'})

        if branch not in repository.get_branches():
            raise forms.ValidationError(
                {"branch": 'Select a valid branch. \
That branch is not one of the available branches.'})

    def validate_domains(self, data: dict):
        """
        Validate the domain selected, updates the value
        of domain key in data passed as input to Type[Domain]

        :param data: Data from form fields
        :type data: dict
        :raises forms.ValidationError: validation error
        """
        domain = data.get('domain')
        try:
            domain: Type[Domain] = Domain.objects.get(id=domain)
            self.validate_subdomain_name(data, domain.domain_id)
            data['domain'] = domain
        except Domain.DoesNotExist:
            raise forms.ValidationError(
                {"domain": 'Select a valid domain. \
That domain is not one of the available domains.'})

    def validate_subdomain_name(self, data: dict, domain_id: str):
        """
        Validate the sub domain selected, updates the value
        of subdomain key in data passed as input to Type[Subdomain]

        :param data: Data from form fields
        :type data: dict
        :param domain_id: selected domain domain_id
        :type domain_id: str
        :raises forms.ValidationError: validation error
        """
        subdomain = data.get('subdomain')
        if subdomain:
            # Validate the selected subdomain belongs to domain
            try:
                subdomain: Type[Subdomain] = Subdomain.objects.get(
                    record_id=subdomain)
                if subdomain.domain_id != domain_id:
                    raise Subdomain.DoesNotExist
                data['subdomain'] = subdomain
            except Subdomain.DoesNotExist:
                raise forms.ValidationError(
                    {"subdomain": 'Select a valid option. \
Selected option is not one of the available subdomains.'})
        else:
            self.validate_link_name(data)

    def validate_link_name(self, data: dict):
        """
        Validate new subdomain name

        :param data: Data from form fields
        :type data: dict
        :raises forms.ValidationError: validation error
        """
        link = data.get('link')
        if not link:
            raise forms.ValidationError(
                {"link": 'Must select a subdomain \
or provide a new one to be created.'})

    def clean(self) -> CleanDataType:
        """
        _summary_

        :return: _description_
        :rtype: CleanDataType
        """
        # self.cleaned_data: CleanDataType = self.cleaned_data
        cleaned_data = self.cleaned_data

        self.validate_domains(cleaned_data)
        self.validate_git(cleaned_data)

        return cleaned_data

monitor/deployer/templates/deployer/deploy-react-app.html
{% extends 'panel/base.html' %}
{% load static %}

{% block css_plugins %}
    <link href="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/css/select2.min.css" rel="stylesheet" />
{% endblock css_plugins %}

{% block content %}
    <div class="py-3 d-flex align-items-center justify-content-end">
        <a href="{% url 'deploy:react' %}" class='btn btn-sm btn-primary'> <span class='fa fa-arrow-left'></span> Back to apps</a>
    </div>

    <form id='deploy-react-form' class="custom-deploy-form mb-5" method='post'
    success_text="Deployed app is valid, and is being deployed successfully."
    error_text = "Error occured while trying to deploy app, check errors.">
        {% csrf_token %}
        <div class="mb-3">
            <label for="#name-input-p">Project Name</label>
            <input type="text" name="project_name" id="name-input-p" class="form-control">
            <div class="form-errors"></div>
        </div>

        <div class="mb-3">
            <label for="#repo-input-p">Github Project Repository</label>
            <select name="repository" id="repo-input-p" class="form-select cSelect">

                <option value="" title=''>-Choose a repository-</option>

                {% for repo in repos %}
                    <option value="{{ repo.id }}" title={{ repo.branches }}>{{ repo.name }}</option>
                {% endfor %}
                
            </select>
            <div class="form-errors"></div>
        </div>

        <div class="mb-3">
            <label for="#branch-input-p">Github Repository Branch</label>
            <select name="branch" id="branch-input-p" class="form-select cSelect">
                
            </select>
            <div class="form-errors"></div>
        </div>

        <div class="mb-3">
            <label for="#domain-input-p">Domain Master</label>
            <select name="domain" id="domain-input-p" class="form-select cSelect">
                <option value="" title=''>-Choose a domain-</option>

                {% for domain in domains %}
                    <option value="{{ domain.id }}" title={{ domain.get_subdomain_js_string }}>{{ domain.domain }}</option>
                {% endfor %}
            </select>
            <div class="form-errors"></div>
        </div>

        <div class="mb-3">
            <label for="#subdomain-input-p" class='d-flex align-items-center justify-content-between'>Subdomain 
                <span id="new-subdomain-form-btn" class='btn btn-outline-primary label-side'><i class="fa fa-plus"></i>New</span>
                <span id="select-subdomain-form-btn" class='btn btn-outline-primary label-side d-none'><i class="fa fa-check-square-o"></i>Select</span>
            </label>

            <select name="subdomain" id="subdomain-input-p" class="form-select cSelect">
            </select>

            <div id='subdomain-input-new' class="input-group d-none">
                <input type="text" name="link" id="link-input-p" class="form-control">
                <div class="input-group-text"></div>
            </div>

            <div class="form-errors"></div>
        </div>

        <button type="submit" class="btn btn-lg btn-success mt-5 fw-bold"><span class="fa fa-cloud-upload"></span>Deploy</button>

    </form>
{% endblock content %}

{% block js_plugins %}
    <script src="https://cdn.jsdelivr.net/npm/select2@4.1.0-rc.0/dist/js/select2.min.js"></script>
{% endblock js_plugins %}

monitor/deployer/templates/deployer/deploys.html
{% extends 'panel/base.html' %}


{% block content %}
    <div class="py-3 d-flex align-items-center justify-content-end">
        <a href="{% url 'deploy:react-new' %}" class='btn btn-primary'> <span class='fa fa-codepen'></span> Deploy new app</a>
    </div>

    <div class="apps-list">


        {% if apps.count == 0 %}

            <div class="bg-secondary text-light rounded p-4 my-5">
                <h5>No React apps are deployed yet</h5>
            </div>

        {% endif %}


        {% for app in apps %}
            <div class="app-box">
                <div class="app-content">
                    <h6>Project Name</h6>
                    <p>{{ app.project_name }}</p>
                </div>
                <div class="app-content">
                    <h6>Project Location</h6>
                    <p>{{ app.get_app_dir }}</p>
                </div>
                <div class="app-content">
                    <h6>Conf. Location</h6>
                    <p>{{ app.get_apache_conf }}</p>
                </div>

                <div class="app-top-btn">
                    <p class="badge status-btn {{ app.status }}">{{ app.get_status_display }}</p>
                    <a href="{% url 'deploy:react-app' app.slug %}" class="btn btn-primary">View App</a>
                </div>
            </div>
        {% endfor %}


    </div>

    
{% endblock content %}

monitor/deployer/templates/deployer/detail.html
{% extends 'panel/base.html' %}


{% block content %}

<div class="py-3 d-flex align-items-center justify-content-end">
    <a href="{% url 'deploy:react' %}" class='btn btn-sm btn-primary'> <span class='fa fa-arrow-left'></span> Back to apps</a>
</div>


<div class="row mb-4">
    <div class="col-md-12">
        <div class="card deploy-dets-box my-3">
            <div class="card-body">
                <h5 class="mb-3">Project</h5>

                <div class="info-ps">
                    <div class="info-p">
                        <small>Name</small>
                        <p>{{ app.project_name }}</p>
                    </div>
                    <div class="info-p">
                        <small>Directory</small>
                        <p>{{ app.get_app_dir }}</p>
                    </div>
                    <div class="info-p">
                        <small>Deploy log</small>
                        <p>{{ app.get_log_file }}</p>
                    </div>
                    <div class="info-p">
                        <small>Status</small>
                        <p class='status-btn {{ app.status }}'><span><i class='fa fa-{{ app.get_status_icon }}'></i></span> {{ app.get_status_display }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer justify-content-start">
                <a href="{% url 'deploy:deploy-react-app' app.slug %}" class="btn btn-primary ms-0"><span><i class="fa fa-refresh"></i></span> Redeploy</a>
                <a href="#" class="btn btn-outline-danger"><span><i class="fa fa-trash"></i></span> Destroy</a>
                <a type="button" data-bs-toggle="modal" data-bs-target="#logModalContent" class="btn btn-outline-secondary"><span><i class="fa fa-info-circle"></i></span> Logs</a>

                
                {% if not app.auto_redeploy %}
                    <a href="{% url 'deploy:setup-redeploy' app.slug %}" class="btn btn-outline-primary"><span><i class="fa fa-check"></i></span> Activate Auto Redeploy</a>
                {% else %}
                    <a href="{% url 'deploy:setup-redeploy' app.slug %}" class="btn btn-outline-danger"><span><i class="fa fa-times"></i></span> Deactivate Auto Redeploy</a>
                {% endif %}
                    
                
            </div>
        </div>
    </div>

    
    
    <div class="col-md-6">
        <div class="card deploy-dets-box my-3">
            <div class="card-body">
                <h5 class="mb-3">Project Github</h5>

                <div class="info-ps">
                    <div class="info-p">
                        <small>Repository</small>
                        <p>{{ app.repository.name }}</p>
                    </div>
                    <div class="info-p">
                        <small>Branch</small>
                        {% if app.branch %}
                            <p>{{ app.branch }}</p>
                        {% else %}
                            <p>Master Branch</p>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="{% url 'deploy:pull-app' app.slug %}" class="btn btn-sm btn-outline-primary"><span><i class="fa fa-cloud-download"></i></span> Pull</a>
                <a href="#" class="btn btn-sm btn-outline-primary"><span><i class="fa fa-edit"></i></span> Edit</a>
            </div>
        </div>
    </div>

    

    <div class="col-md-6">
        <div class="card deploy-dets-box my-3">
            <div class="card-body">
                <h5 class="mb-3">Web Server</h5>

                <div class="info-ps">
                    <div class="info-p">
                        <small>Configuration File</small>
                        <p>{{ app.get_web_server_conf }}</p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-sm btn-secondary"><span><i class="fa fa-pause-circle"></i></span> Disable</a>
                <a href="#" class="btn btn-sm btn-secondary"><span><i class="fa fa-info-circle"></i></span> Check Logs</a>
                <a href="#" class="btn btn-sm btn-outline-primary"><span><i class="fa fa-edit"></i></span> Edit</a>
            </div>
        </div>
    </div>
    
    <div class="col-md-7">
        <div class="card deploy-dets-box my-3">
            <div class="card-body">
                <h5 class="mb-3">Domain</h5>

                <div class="info-ps">
                    <div class="info-p">
                        <small>Main Domain</small>
                        <p>{{ app.domain.domain }}</p>
                    </div>
                    <div class="info-p">
                        <small>Subdomain</small>
                        <p>{{ app.subdomain.name }}</p>
                    </div>
                    <div class="info-p">
                        <small>Link</small>
                        <p><a class='link-with-icon' href='{{ app.get_link }}' target="blank"><span><i class="fa fa-link"></i></span>{{ app.get_link }}</a></p>
                    </div>
                </div>
            </div>
            <div class="card-footer">
                <a href="#" class="btn btn-sm btn-outline-primary"><span><i class="fa fa-edit"></i></span> Edit</a>
            </div>
        </div>
    </div>
</div>


<!-- Log Modal -->
<div class="modal fade" id="logModalContent" tabindex="-1" aria-labelledby="logModal" aria-hidden="true" log="{% url 'deploy:deploy-app-logs' app.slug %}">
    <div class="modal-dialog modal-dialog-scrollable">
        <div class="modal-content">
            <div class="modal-header">
                <h5 class="modal-title" id="logModal">Deploy Logs</h5>
                <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">

                <p class='content' style="white-space: break-spaces;">
                    No logs yet
                </p>
                
            </div>
            <div class="modal-footer">
                <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
                <form id='logForm' method="POST">
                    {% csrf_token %}
                    <button type="submit" class="btn btn-primary clearLogs">Clear Logs</button>
                </form>
            </div>
        </div>
    </div>
</div>
    


    
{% endblock content %}